[package]
name = "win-rawcap"
version = "0.1.0"
authors = ["Harry Cheng <chengyuhui1@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.3", features = ["full"] }
anyhow = "1.0.34"
winapi = "0.3.9"
socket2 = "0.3.16"
etherparse = "0.9.0"
